# Generated by Django 5.2.6 on 2025-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_footer_footerlink_newslettertext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='twitter_url',
            new_name='whatsapp_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='copyright_text',
        ),
        migrations.AddField(
            model_name='footer',
            name='about_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_title',
            field=models.CharField(default='PetPalooza', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='categories_title',
            field=models.CharField(default='Categories', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='subscribe_text',
            field=models.CharField(default='For Subscribe', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='support_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='support_title',
            field=models.CharField(default='Support', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
