# Generated by Django 5.2.6 on 2025-09-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_herobanner_promobanner_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mission', models.TextField()),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('description_title', models.CharField(default='ANYTHING FOR PETS®', max_length=200)),
                ('description', models.TextField()),
                ('card1_title', models.CharField(default='Our story', max_length=100)),
                ('card1_image', models.ImageField(blank=True, null=True, upload_to='about/cards/')),
                ('card1_link', models.CharField(blank=True, max_length=200, null=True)),
                ('card2_title', models.CharField(default='Media resources', max_length=100)),
                ('card2_image', models.ImageField(blank=True, null=True, upload_to='about/cards/')),
                ('card2_link', models.CharField(blank=True, max_length=200, null=True)),
                ('card3_title', models.CharField(default='Charities', max_length=100)),
                ('card3_image', models.ImageField(blank=True, null=True, upload_to='about/cards/')),
                ('card3_link', models.CharField(blank=True, max_length=200, null=True)),
                ('bottom_title', models.CharField(blank=True, max_length=200, null=True)),
                ('bottom_text', models.TextField(blank=True, null=True)),
                ('bottom_image', models.ImageField(blank=True, null=True, upload_to='about/bottom/')),
            ],
        ),
    ]
